### ISSUE TITLE
Bad recommendation

### ISSUE THREAD

**Issue by JasonN3** [linux-system-roles/ad_integration#22]
It is **never** recommended to use the domain admin account to do anything. Least privileged access should always be utilized. Especially for service accounts.

https://github.com/linux-system-roles/ad_integration/blob/803ebb0bd890dc180ecc73240438d05d67e88d14/README.md?plain=1#L12

**Comment by richm** [comment]
What would you recommend?  Something like this:
```
In order to join to the domain, you must use an Active Directory user which has sufficient join permissions. 
It is not recommended to use the Administrator user as the security footprint of this user is too large.
```
?

**Comment by JasonN3** [comment]
That works for me. Including a list of what permissions are required would also be great. It would make it easier to get the account setup properly without having to identify the permissions yourself.

**Comment by richm** [comment]
> That works for me. Including a list of what permissions are required would also be great. It would make it easier to get the account setup properly without having to identify the permissions yourself.

@justin-stephenson Do you know what specific permissions are required?  Given a user, is there a way to verify that it has the required permissions before attempting to use the role?

**Comment by JasonN3** [comment]
Even though it's not stored on each machine, domain admin should still not be used for any actions. It's bad practice and shouldn't be encouraged.

Referencing the `DELEGATED PERMISSIONS` section of the `ADCLI(8)` man page would work. It does a good job of showing what permissions are required for which actions.

**Comment by richm** [comment]
> Even though it's not stored on each machine, domain admin should still not be used for any actions. It's bad practice and shouldn't be encouraged.
> 
> Referencing the `DELEGATED PERMISSIONS` section of the `ADCLI(8)` man page would work. It does a good job of showing what permissions are required for which actions.

The various adcli man pages  I have been able to find (e.g. https://manpages.org/adcli/8) do not have a "DELEGATED PERMISSIONS" section.  Is there a link to some sort of adcli documentation that describes these permissions/

**Comment by JasonN3** [comment]
> > Even though it's not stored on each machine, domain admin should still not be used for any actions. It's bad practice and shouldn't be encouraged.
> > Referencing the `DELEGATED PERMISSIONS` section of the `ADCLI(8)` man page would work. It does a good job of showing what permissions are required for which actions.
> 
> The various adcli man pages I have been able to find (e.g. https://manpages.org/adcli/8) do not have a "DELEGATED PERMISSIONS" section. Is there a link to some sort of adcli documentation that describes these permissions/

Odd. It's available when I run `man adcli` on a CentOS Stream 8 system and at https://manpages.debian.org/testing/adcli/adcli.8.en.html

**Comment by JasonN3** [comment]
The new phrasing looks good to me
