### ISSUE TITLE
ad_integration_sssd_custom_settings not required SSSD restart ?

### ISSUE THREAD

**Issue by seb2020** [linux-system-roles/ad_integration#75]
Hi,

If I use the variable "ad_integration_sssd_custom_settings" and set additional parameters, the configuration file is correctly update. After the configuration, the handler "Handler for ad_integration to restart services" is called.

By default, the handler restart all services defined in "__ad_integration_services" : "realmd"

Is this normal that by default there is no "sssd" in the "__ad_integration_services" ?

**Comment by justin-stephenson** [comment]
Hi, looks like the `sssd` should be added here to the services listed here. Could you submit a PR?

-Justin

**Comment by seb2020** [comment]
It will be resolved by PR#76  https://github.com/linux-system-roles/ad_integration/pull/76 because I have created a specific handler for sssd

**Comment by seb2020** [comment]
Resolved with https://github.com/linux-system-roles/ad_integration/pull/76
